services:
  invertus.dpdbaltics.builder.template.admin.info_block_builder:
    class: 'Invertus\dpdBaltics\Builder\Template\Admin\InfoBlockBuilder'
    arguments:
      - '@dpdbaltics'

  invertus.dpdbaltics.builder.template.admin.warning_block_builder:
    class: 'Invertus\dpdBaltics\Builder\Template\Admin\WarningBlockBuilder'
    arguments:
      - '@dpdbaltics'

  invertus.dpdbaltics.builder.template.admin.product_block_builder:
    class: 'Invertus\dpdBaltics\Builder\Template\Admin\ProductBlockBuilder'
    arguments:
      - '@dpdbaltics'
      - '@smarty'
      - '@language'
      - '@invertus.dpdbaltics.repository.product_repository'
      - '@invertus.dpdbaltics.repository.product_zone_repository'
      - '@invertus.dpdbaltics.repository.product_shop_repository'
      - '@invertus.dpdbaltics.service.language_service'
      - '@invertus.dpdbaltics.builder.template.search_box_builder'

  invertus.dpdbaltics.builder.template.front.carrier_options_builder:
    class: 'Invertus\dpdBaltics\Builder\Template\Front\CarrierOptionsBuilder'
    arguments:
      - '@context'
      - '@invertus.dpdbaltics.repository.price_rule_repository'
      - '@invertus.dpdbaltics.provider.product_shipping_cost_provider'
      - '@=service("dpdbaltics").getLocalPath()'
      - '@invertus.dpdbaltics.repository.carrier_repository'

  invertus.dpdbaltics.builder.carrier_builder:
    class: 'Invertus\dpdBaltics\Builder\CarrierBuilder'
    arguments:
      - '@dpdbaltics'

  invertus.dpdbaltics.builder.carrier_image_builder:
    class: 'Invertus\dpdBaltics\Builder\CarrierImageBuilder'
    arguments:
      - '@dpdbaltics'

  invertus.dpdbaltics.builder.template.search_box_builder:
    class: 'Invertus\dpdBaltics\Builder\Template\SearchBoxBuilder'
    arguments:
      - '@dpdbaltics'
      - '@smarty'

  invertus.dpdbaltics.builder.template.admin.phone_input_builder:
    class: 'Invertus\dpdBaltics\Builder\Template\Admin\PhoneInputBuilder'
    arguments:
      - '@dpdbaltics'
      - '@smarty'