services:
  invertus.dpdbaltics.console_command.update_parcel_shops_command:
    class : 'Invertus\dpdBaltics\ConsoleCommand\UpdateParcelShopsCommand'
    arguments:
      - '@invertus.dpdbaltics.logger.logger'
      - '@invertus.dpdbaltics.service.import.api.parcel_shop_import'
    tags:
      - { name: 'console.command', command: 'dpdbaltics:update-parcel-shops'}