services:
  invertus.dpdbaltics.service.export.export_provider:
    class: 'Invertus\dpdBaltics\Service\Export\ExportProvider'
    arguments:
      - '@dpdbaltics'

  invertus.dpdbaltics.service.export.zone_export:
    class: 'Invertus\dpdBaltics\Service\Export\ZoneExport'
    arguments:
      - '@dpdbaltics'

  invertus.dpdbaltics.service.export.settings_export:
    class: 'Invertus\dpdBaltics\Service\Export\SettingsExport'
    arguments:
      - '@dpdbaltics'

  invertus.dpdbaltics.service.export.address_templates_export:
    class: 'Invertus\dpdBaltics\Service\Export\AddressTemplatesExport'
    arguments:
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.repository.address_template_repository'

  invertus.dpdbaltics.service.export.product_export:
    class: 'Invertus\dpdBaltics\Service\Export\ProductExport'
    arguments:
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.repository.product_repository'
      - '@invertus.dpdbaltics.repository.zone_repository'
      - '@invertus.dpdbaltics.repository.product_shop_repository'
      - '@invertus.dpdbaltics.repository.product_availability_repository'

  invertus.dpdbaltics.service.export.price_rules_export:
    class: 'Invertus\dpdBaltics\Service\Export\PriceRulesExport'
    arguments:
      - '@invertus.dpdbaltics.repository.price_rule_repository'
      - '@dpdbaltics'
