services:
  invertus.dpdbaltics.factory.array_factory:
    class: 'Invertus\dpdBaltics\Factory\ArrayFactory'

  invertus.dpdbaltics_factory.context_factory:
    class: 'Invertus\dpdBaltics\Factory\ContextFactory'

  invertus.dpdbaltics.factory.tab_factory:
    class: 'Invertus\dpdBaltics\Factory\TabFactory'
    arguments:
      - '@invertus.dpdbaltics.service.tab_service'

  invertus.dpdbaltics.factory.apiparams_factory:
    class: 'Invertus\dpdBaltics\Factory\APIParamsFactory'
    arguments:
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.config.api_configuration'

  invertus.dpdbaltics.factory.shipment_data_factory:
    class: 'Invertus\dpdBaltics\Factory\ShipmentDataFactory'
    arguments:
      - '@invertus.dpdbaltics.repository.order_repository'
      - '@invertus.dpdbaltics.repository.shipment_repository'
      - '@invertus.dpdbaltics.repository.pudo_repository'

  invertus.dpdbaltics.factory.shop_factory:
    class: 'Invertus\dpdBaltics\Factory\ShopFactory'
    arguments:
    - '@invertus.dpdbaltics.repository.parcel_shop_repository'

  invertus.dpdbaltics.factory.parcel_tracking_url_factory:
    class: 'Invertus\dpdBaltics\Factory\ParcelTrackingUrlFactory'
    arguments:
      - '@invertus.dpdbaltics.provider.current_country_provider'
      - '@invertus.dpdbaltics.repository.parcel_shop_repository'

  invertus-dpdbaltics-factory-parcel_tracking_url_factory:
    class: 'Invertus\dpdBaltics\Factory\ParcelTrackingUrlFactory'
    arguments:
      - '@invertus.dpdbaltics.provider.current_country_provider'


