services:
  invertus.dpdbaltics.service.import.settings_import:
    class: 'Invertus\dpdBaltics\Service\Import\SettingsImport'
    arguments:
      - '@dpdbaltics'

  invertus.dpdbaltics.service.import.zone_import:
    class: 'Invertus\dpdBaltics\Service\Import\ZoneImport'
    arguments:
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.orm.entity_manager'
      - '@invertus.dpdbaltics.adapter.zone_adapter'
      - '@invertus.dpdbaltics.validate.zone.zone_range_validate'
      - '@invertus.dpdbaltics.repository.dpdzone_repository'
      - '@smarty'

  invertus.dpdbaltics.service.import.import_main_zone:
    class: 'Invertus\dpdBaltics\Service\Import\ImportMainZone'
    arguments:
      - '@invertus.dpdbaltics.service.import.import_provider'
      - '@invertus.dpdbaltics.service.import.zone_import'

  invertus.dpdbaltics.service.import.import_provider:
    class: 'Invertus\dpdBaltics\Service\Import\ImportProvider'
    arguments:
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.adapter.dpdconfiguration_adapter'

  invertus.dpdbaltics.service.import.product_import:
    class: 'Invertus\dpdBaltics\Service\Import\ProductImport'
    arguments:
      - '@invertus.dpdbaltics.repository.product_repository'
      - '@invertus.dpdbaltics.repository.zone_repository'
      - '@invertus.dpdbaltics.repository.shop_repository'
      - '@invertus.dpdbaltics.repository.product_availability_repository'

  invertus.dpdbaltics.service.import.price_rules_import:
    class: 'Invertus\dpdBaltics\Service\Import\PriceRulesImport'
    arguments:
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.repository.price_rule_repository'
      - '@invertus.dpdbaltics.repository.dpdzone_repository'
      - '@invertus.dpdbaltics.repository.carrier_repository'

  invertus.dpdbaltics.service.import.address_templates_import:
    class: 'Invertus\dpdBaltics\Service\Import\AddressTemplatesImport'
    arguments:
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.repository.shop_repository'

  invertus.dpdbaltics.service.import.zip_import:
    class: 'Invertus\dpdBaltics\Service\Import\ZipImport'
    arguments:
      - '@dpdbaltics'
      - '@smarty'