services:
  invertus.dpdbaltics.on_board.builder.on_board_block_builder:
    class: 'Invertus\dpdBaltics\OnBoard\Builder\OnBoardBlockBuilder'
    arguments:
      - '@dpdbaltics'
      - '@smarty'

  invertus.dpdbaltics.on_board.abstract_on_board_step:
    class: 'Invertus\dpdBaltics\OnBoard\AbstractOnBoardStep'
    abstract: true
    arguments:
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.on_board.service.on_board_step_action_service'
      - '@invertus.dpdbaltics.on_board.service.on_board_step_data_service'

  invertus.dpdbaltics.on_board.provider.on_board_step_strategy_provider:
    class: 'Invertus\dpdBaltics\OnBoard\Provider\OnBoardStepStrategyProvider'
    arguments:
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_import_1'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_import_2'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_import_finish'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_main_1'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_main_2'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_main_3'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_main_3'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_config_finish'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_0'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_1'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_2'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_3'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_4'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_5'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_6'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_7'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_8'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_0'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_1'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_2'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_3'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_4'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_5'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_5_shop'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_6'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_7'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_8'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_9'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_0'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_1'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_2'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_3'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_4'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_5'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_6'
      - '@invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_after_import'

  invertus.dpdbaltics.on_board.service.on_board_step_action_service:
    class: 'Invertus\dpdBaltics\OnBoard\Service\OnBoardStepActionService'
    arguments:
      - '@dpdBaltics'
      - '@controller'
      - '@cookie'

  invertus.dpdbaltics.on_board.service.on_board_step_data_service:
    class: 'Invertus\dpdBaltics\OnBoard\Service\OnBoardStepDataService'
    arguments:
      - '@dpdBaltics'
      - '@cookie'
      - '@invertus.dpdbaltics.repository.zone_repository'
      - '@invertus.dpdbaltics.repository.price_rule_repository'
      - '@invertus.dpdbaltics.repository.product_repository'

  invertus.dpdbaltics.on_board.service.on_board_service:
    class: 'Invertus\dpdBaltics\OnBoard\Service\OnBoardService'
    arguments:
      - '@invertus.dpdbaltics.on_board.provider.on_board_step_strategy_provider'
      - '@invertus.dpdbaltics.on_board.builder.on_board_block_builder'

  invertus.dpdbaltics.on_board.on_board_steps.step_import_1:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepImport1'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_import_2:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepImport2'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_import_finish:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepImportFinish'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_main_1:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepMain1'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_main_2:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepMain2'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_main_3:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepMain3'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_config_finish:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualConfigFinish'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_0:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualPriceRules0'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_1:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualPriceRules1'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_2:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualPriceRules2'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_3:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualPriceRules3'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_4:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualPriceRules4'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_5:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualPriceRules5'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_6:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualPriceRules6'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_7:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualPriceRules7'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_price_rules_8:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualPriceRules8'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_0:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualProducts0'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_1:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualProducts1'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_2:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualProducts2'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_3:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualProducts3'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_4:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualProducts4'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_5:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualProducts5'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_5_shop:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualProducts5Shop'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_6:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualProducts6'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_7:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualProducts7'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_8:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualProducts8'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_products_9:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualProducts9'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_0:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualZones0'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_1:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualZones1'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_2:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualZones2'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_3:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualZones3'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_4:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualZones4'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_5:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualZones5'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_6:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualZones6'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'

  invertus.dpdbaltics.on_board.on_board_steps.step_manual_zones_after_import:
    class: 'Invertus\dpdBaltics\OnBoard\OnBoardSteps\StepManualZonesAfterImport'
    parent: 'invertus.dpdbaltics.on_board.abstract_on_board_step'