services:
  invertus.dpdbaltics.presenter.delivery_time_presenter:
    class: 'Invertus\dpdBaltics\Presenter\DeliveryTimePresenter'
    arguments:
      - '@context'
      - '@dpdbaltics'

  invertus.dpdbaltics.presenter.same_day_delivery_message_presenter:
    class: 'Invertus\dpdBaltics\Presenter\SameDayDeliveryMessagePresenter'
    arguments:
      - '@context'
      - '@dpdbaltics'