services:
  invertus.dpdbaltics.provider.import_export_options_provider:
    class: 'Invertus\dpdBaltics\Provider\ImportExportOptionsProvider'
    arguments:
      - '@dpdbaltics'

  invertus.dpdbaltics.provider.import_export_url_provider:
    class: 'Invertus\dpdBaltics\Provider\ImportExportURLProvider'
    arguments:
      - '@context'

  invertus.dpdbaltics.provider.product_shipping_cost_provider:
    class: 'Invertus\dpdBaltics\Provider\ProductShippingCostProvider'
    arguments:
      - '@dpdbaltics'
      -  '@invertus.dpdbaltics.repository.product_repository'
      -  '@invertus.dpdbaltics.repository.zone_repository'
      -  '@invertus.dpdbaltics.repository.price_rule_repository'
      -  '@currency'

  invertus.dpdbaltics.provider.zone_range_provider:
    class: 'Invertus\dpdBaltics\Provider\ZoneRangeProvider'
    arguments:
      - '@language'
      - '@invertus.dpdbaltics.repository.zone_range_repository'

  invertus.dpdbaltics.provider.product_availability_provider:
    class: 'Invertus\dpdBaltics\Provider\ProductAvailabilityProvider'
    arguments:
      - '@language'
      - '@invertus.dpdbaltics.repository.product_availability_repository'

  invertus.dpdbaltics.provider.current_country_provider:
    class: 'Invertus\dpdBaltics\Provider\CurrentCountryProvider'
    arguments:
      - '@context'
