services:
  invertus.dpdbaltics.repository.carrier_repository:
    class: 'Invertus\dpdBaltics\Repository\CarrierRepository'

  invertus.dpdbaltics.repository.dpdzone_repository:
    class: 'Invertus\dpdBaltics\Repository\DPDZoneRepository'

  invertus.dpdbaltics.repository.order_repository:
    class: 'Invertus\dpdBaltics\Repository\OrderRepository'

  invertus.dpdbaltics.repository.product_repository:
    class: 'Invertus\dpdBaltics\Repository\ProductRepository'

  invertus.dpdbaltics.repository.product_zone_repository:
    class: 'Invertus\dpdBaltics\Repository\ProductZoneRepository'

  invertus.dpdbaltics.repository.product_shop_repository:
    class: 'Invertus\dpdBaltics\Repository\ProductShopRepository'

  invertus.dpdbaltics.repository.price_rule_repository:
    class: 'Invertus\dpdBaltics\Repository\PriceRuleRepository'

  invertus.dpdbaltics.repository.phone_prefix_repository:
    class: 'Invertus\dpdBaltics\Repository\PhonePrefixRepository'

  invertus.dpdbaltics.repository.zone_repository:
    class: 'Invertus\dpdBaltics\Repository\ZoneRepository'

  invertus.dpdbaltics.repository.zone_range_repository:
    class: 'Invertus\dpdBaltics\Repository\ZoneRangeRepository'

  invertus.dpdbaltics.repository.payment_repository:
    class: 'Invertus\dpdBaltics\Repository\PaymentRepository'

  invertus.dpdbaltics.repository.shipment_repository:
    class: 'Invertus\dpdBaltics\Repository\ShipmentRepository'

  invertus.dpdbaltics.repository.receiver_address_repository:
    class: 'Invertus\dpdBaltics\Repository\ReceiverAddressRepository'

  invertus.dpdbaltics.repository.phone_repository:
    class: 'Invertus\dpdBaltics\Repository\PhoneRepository'

  invertus.dpdbaltics.repository.cod_payment_repository:
    class: 'Invertus\dpdBaltics\Repository\CodPaymentRepository'

  invertus.dpdbaltics.repository.pudo_repository:
    class: 'Invertus\dpdBaltics\Repository\PudoRepository'

  invertus.dpdbaltics.repository.logs_repository:
    class: 'Invertus\dpdBaltics\Repository\LogsRepository'

  invertus.dpdbaltics.repository.address_repository:
    class: 'Invertus\dpdBaltics\Repository\AddressRepository'

  invertus.dpdbaltics.repository.collection_request_repository:
    class: 'Invertus\dpdBaltics\Repository\CollectionRequestRepository'

  invertus.dpdbaltics.repository.courier_request_repository:
    class: 'Invertus\dpdBaltics\Repository\CourierRequestRepository'

  invertus.dpdbaltics.repository.address_template_repository:
    class: 'Invertus\dpdBaltics\Repository\AddressTemplateRepository'

  invertus.dpdbaltics.repository.shop_repository:
    class: 'Invertus\dpdBaltics\Repository\ShopRepository'

  invertus.dpdbaltics.repository.parcel_shop_repository:
    class: 'Invertus\dpdBaltics\Repository\ParcelShopRepository'

  invertus.dpdbaltics.repository.product_availability_repository:
    class: 'Invertus\dpdBaltics\Repository\ProductAvailabilityRepository'

  invertus.dpdbaltics.repository.order_delivery_time_repository:
    class: 'Invertus\dpdBaltics\Repository\OrderDeliveryTimeRepository'
