services:
  invertus.dpdbaltics.service.carrier.create_carrier_service:
    class: 'Invertus\dpdBaltics\Service\Carrier\CreateCarrierService'
    arguments:
      - '@language'
      - '@invertus.dpdbaltics.builder.carrier_builder'
      - '@invertus.dpdbaltics.builder.carrier_image_builder'
      - '@invertus.dpdbaltics.repository.product_repository'

  invertus.dpdbaltics.service.carrier_phone_service:
    class: 'Invertus\dpdBaltics\Service\CarrierPhoneService'
    arguments:
      - '@dpdbaltics'
      - '@context'
      - '@invertus.dpdbaltics.orm.entity_manager'
      - '@invertus.dpdbaltics.repository.phone_prefix_repository'
      - '@invertus.dpdbaltics.repository.order_repository'

  invertus.dpdbaltics.service.carrier.update_carrier_service:
    class: 'Invertus\dpdBaltics\Service\Carrier\UpdateCarrierService'
    arguments:
      - '@invertus.dpdbaltics.service.language_service'
      - '@invertus.dpdbaltics.validate.carrier.carrier_update_validate'

  invertus.dpdbaltics.service.dpdflash_message_service:
    class: 'Invertus\dpdBaltics\Service\DPDFlashMessageService'
    arguments:
      - '@context'

  invertus.dpdbaltics.service.language_service:
    class: 'Invertus\dpdBaltics\Service\LanguageService'

  invertus.dpdbaltics.service.product.product_service:
    class: 'Invertus\dpdBaltics\Service\Product\ProductService'
    arguments:
      - '@invertus.dpdbaltics.repository.product_repository'
      - '@invertus.dpdbaltics.service.carrier.create_carrier_service'

  invertus.dpdbaltics.service.product.product_availability_service:
    class: 'Invertus\dpdBaltics\Service\Product\ProductAvailabilityService'
    arguments:
      - '@invertus.dpdbaltics.repository.product_availability_repository'
      - '@invertus.dpdbaltics.repository.product_repository'

  invertus.dpdbaltics.service.product.update_product_zone_service:
    class: 'Invertus\dpdBaltics\Service\Product\UpdateProductZoneService'
    arguments:
      - '@invertus.dpdbaltics.repository.product_zone_repository'

  invertus.dpdbaltics.service.product.update_product_shop_service:
    class: 'Invertus\dpdBaltics\Service\Product\UpdateProductShopService'
    arguments:
      - '@invertus.dpdbaltics.repository.product_shop_repository'

  invertus.dpdbaltics.service.price_rule_service:
    class: 'Invertus\dpdBaltics\Service\PriceRuleService'
    arguments:
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.repository.price_rule_repository'
      - '@invertus.dpdbaltics.repository.product_repository'
      - '@invertus.dpdbaltics.repository.dpdzone_repository'
      - '@invertus.dpdbaltics.repository.payment_repository'
      - '@invertus.dpdbaltics.repository.carrier_repository'
      - '@invertus.dpdbaltics.repository.shop_repository'
      - '@smarty'
      - '@language'
      - '@shop'

  invertus.dpdbaltics.service.tab_service:
    class: 'Invertus\dpdBaltics\Service\TabService'
    arguments:
      - '@dpdbaltics'

  invertus.dpdbaltics.service.zone.delete_zone_service:
    class: 'Invertus\dpdBaltics\Service\Zone\DeleteZoneService'
    arguments:
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.repository.carrier_repository'
      - '@invertus.dpdbaltics.repository.price_rule_repository'
      - '@invertus.dpdbaltics.factory.array_factory'

  invertus.dpdbaltics.service.zone.update_zone_service:
    class: 'Invertus\dpdBaltics\Service\Zone\UpdateZoneService'

  invertus.dpdbaltics.service.shipment_service:
    class: 'Invertus\dpdBaltics\Service\ShipmentService'
    arguments:
    - '@dpdbaltics'
    - '@language'
    - '@invertus.dpdbaltics.repository.shipment_repository'
    - '@invertus.dpdbaltics.helper.shipment_helper'
    - '@invertus.dpdbaltics.service.api.shipment_api_service'
    - '@invertus.dpdbaltics.validate.shipment_data.shipment_data_validator'
    - '@invertus.dpdbaltics.service.exception.exception_service'
    - '@invertus.dpdbaltics.service.label.label_printing_service'
    - '@invertus.dpdbaltics.service.pudo_service'
    - '@invertus.dpdbaltics.repository.order_delivery_time_repository'
    - '@invertus.dpdbaltics.factory.shipment_data_factory'
    - '@invertus.dpdbaltics.service.order_service'
    - '@invertus.dpdbaltics.validate.carrier.carrier_update_validate'
    - '@invertus.dpdbaltics.logger.logger'

  invertus.dpdbaltics.service.label.label_printing_service:
    class: 'Invertus\dpdBaltics\Service\Label\LabelPrintingService'
    arguments:
    - '@dpdbaltics'
    - '@invertus.dpdbaltics.service.api.shipment_api_service'
    - '@invertus.dpdbaltics.service.exception.exception_service'
    - '@invertus.dpdbaltics.logger.logger'

  invertus.dpdbaltics.service.label.label_url_formatter:
    class: 'Invertus\dpdBaltics\Service\Label\LabelUrlFormatter'
    arguments:
      - '@invertus.dpdbaltics.adapter.link_adapter'

  invertus.dpdbaltics.service.address.receiver_address_service:
    class: 'Invertus\dpdBaltics\Service\Address\ReceiverAddressService'
    arguments:
      - '@dpdbaltics'
      - '@smarty'
      - '@language'
      - '@invertus.dpdbaltics.repository.receiver_address_repository'
      - '@invertus.dpdbaltics.repository.order_repository'
      - '@invertus.dpdbaltics.service.shipment_service'
      - '@invertus.dpdbaltics.repository.phone_prefix_repository'
      - '@invertus.dpdbaltics.service.order_service'

  invertus.dpdbaltics.service.address.address_template_service:
    class: 'Invertus\dpdBaltics\Service\Address\AddressTemplateService'
    arguments:
      - '@invertus.dpdbaltics.repository.shop_repository'

  invertus.dpdbaltics.service.label.label_position_service:
    class: 'Invertus\dpdBaltics\Service\Label\LabelPositionService'
    arguments:
      - '@dpdbaltics'
      - '@Smarty'

  invertus.dpdbaltics.service.order_service:
    class: 'Invertus\dpdBaltics\Service\OrderService'
    arguments:
      - '@dpdbaltics'

  invertus.dpdbaltics.service.payment.payment_service:
    class: 'Invertus\dpdBaltics\Service\Payment\PaymentService'
    arguments:
      - '@invertus.dpdbaltics.repository.cod_payment_repository'
      - '@invertus.dpdbaltics.repository.pudo_repository'
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.repository.product_repository'
      - '@invertus.dpdbaltics.repository.price_rule_repository'
      - '@shop'

  invertus.dpdbaltics.service.api.shipment_api_service:
    class: 'Invertus\dpdBaltics\Service\API\ShipmentApiService'
    arguments:
      - '@invertus.dpdbaltics_api.factory.apirequest.shipment_creation_factory'
      - '@invertus.dpdbaltics.repository.cod_payment_repository'
      - '@invertus.dpdbaltics.repository.parcel_tracking_email_handler'
      - '@invertus.dpdbaltics.service.parcel.parcel_shop_service'
      - '@invertus.dpdbaltics.adapter.address_adapter'

  invertus.dpdbaltics.service.api.label_api_service:
    class: 'Invertus\dpdBaltics\Service\API\LabelApiService'
    arguments:
      - '@invertus.dpdbaltics.util.file_download'
      - '@invertus.dpdbaltics_api.factory.apirequest.parcel_print_factory'

  invertus.dpdbaltics.service.api.parcel_shop_search_api_service:
    class: 'Invertus\dpdBaltics\Service\API\ParcelShopSearchApiService'
    arguments:
      - '@invertus.dpdbaltics_api.factory.apirequest.parcel_shop_search_factory'

  invertus.dpdbaltics.service.pudo_service:
    class: 'Invertus\dpdBaltics\Service\PudoService'
    arguments:
      - '@invertus.dpdbaltics.repository.pudo_repository'
      - '@smarty'
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.service.api.parcel_shop_search_api_service'
      - '@language'
      - '@invertus.dpdbaltics.service.google_api_service'
      - '@invertus.dpdbaltics.repository.parcel_shop_repository'
      - '@invertus.dpdbaltics.factory.shop_factory'

  invertus.dpdbaltics.service.google_api_service:
    class: 'Invertus\dpdBaltics\Service\GoogleApiService'
    arguments:
      - '@language'
      - '@shop'

  invertus.dpdbaltics.logger.logger:
    class: 'Invertus\dpdBaltics\Logger\Logger'
    arguments:
      - '@invertus.dpdbaltics.service.logs_service'

  invertus.dpdbaltics.service.logs_service:
    class: 'Invertus\dpdBaltics\Service\LogsService'
    arguments:
      - '@invertus.dpdbaltics.repository.logs_repository'
      - '@dpdbaltics'

  invertus.dpdbaltics.service.api.collection_request_service:
    class: 'Invertus\dpdBaltics\Service\API\CollectionRequestService'
    arguments:
      - '@invertus.dpdbaltics_api.factory.apirequest.collection_request_factory'
      - '@dpdbaltics'

  invertus.dpdbaltics.service.api.courier_request_service:
    class: 'Invertus\dpdBaltics\Service\API\CourierRequestService'
    arguments:
      - '@invertus.dpdbaltics_api.factory.apirequest.courier_request_factory'
      - '@dpdbaltics'

  invertus.dpdbaltics.service.parcel.parcel_update_service:
    class: 'Invertus\dpdBaltics\Service\Parcel\ParcelUpdateService'
    arguments:
      - '@invertus.dpdbaltics.repository.parcel_shop_repository'

  invertus.dpdbaltics.service.parcel.parcel_shop_service:
    class: 'Invertus\dpdBaltics\Service\Parcel\ParcelShopService'
    arguments:
      - '@invertus.dpdbaltics.repository.parcel_shop_repository'
      - '@invertus.dpdbaltics.factory.shop_factory'

  invertus.dpdbaltics.service.order_delivery_time_service:
    class: 'Invertus\dpdBaltics\Service\OrderDeliveryTimeService'
    arguments:
      - '@invertus.dpdbaltics.repository.order_delivery_time_repository'

  invertus.dpdbaltics.service.tracking_service:
    class: 'Invertus\dpdBaltics\Service\TrackingService'

  invertus.dpdbaltics.service.exception.exception_service:
    class: 'Invertus\dpdBaltics\Service\Exception\ExceptionService'
    arguments:
      - '@dpdbaltics'

  invertus.dpdbaltics.service.import.api.parcel_shop_import:
    class: 'Invertus\dpdBaltics\Service\Import\API\ParcelShopImport'
    arguments:
      - '@invertus.dpdbaltics.service.api.parcel_shop_search_api_service'
      - '@invertus.dpdbaltics.service.parcel.parcel_update_service'
      - '@dpdbaltics'

      # AccessibilityChecker
  invertus.dpdbaltics.grid.row.print_accessibility_checker:
    class: 'Invertus\dpdBaltics\Grid\Row\PrintAccessibilityChecker'
    arguments:
      - '@invertus.dpdbaltics.repository.shipment_repository'

  invertus.dpdbaltics.service.carrier.carrier_update_handler:
    class: 'Invertus\dpdBaltics\Service\Carrier\CarrierUpdateHandler'
    arguments:
      - '@invertus.dpdbaltics.repository.product_repository'
      - '@invertus.dpdbaltics.service.carrier.update_carrier_service'
      - '@invertus.dpdbaltics.service.product.product_service'

  invertus.dpdbaltics.repository.parcel_tracking_email_handler:
    class: 'Invertus\dpdBaltics\Service\Email\Handler\ParcelTrackingEmailHandler'
    arguments:
      - '@invertus.dpdbaltics.factory.parcel_tracking_url_factory'
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.logger.logger'

  invertus.dpdbaltics.service.carrier.prestashop_carrier_regeneration_handler:
    class: 'Invertus\dpdBaltics\Service\Carrier\PrestashopCarrierRegenerationHandler'
    arguments:
      - '@invertus.dpdbaltics.install.installer'
      - '@invertus.dpdbaltics.repository.product_repository'
      - '@invertus.dpdbaltics.service.carrier.update_carrier_service'
      - '@invertus.dpdbaltics.service.product.product_service'

  invertus-dpdbaltics-repository-parceltrackingemailhandler:
    class: 'Invertus\dpdBaltics\Service\Email\Handler\ParcelTrackingEmailHandler'
    arguments:
      - '@invertus.dpdbaltics.factory.parcel_tracking_url_factory'
      - '@dpdbaltics'
