services:
  invertus.dpdbaltics.validate.zone.zone_range_validate:
    class: 'Invertus\dpdBaltics\Validate\Zone\ZoneRangeValidate'
    arguments:
      - '@dpdbaltics'
      - '@language'

  invertus.dpdbaltics.validate.zone.zone_delete_validate:
    class: 'Invertus\dpdBaltics\Validate\Zone\ZoneDeleteValidate'
    arguments:
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.orm.entity_manager'


  invertus.dpdbaltics.validate.carrier.carrier_update_validate:
    class: 'Invertus\dpdBaltics\Validate\Carrier\CarrierUpdateValidate'
    arguments:
      - '@dpdbaltics'

  invertus.dpdbaltics.validate.carrier.pudo_validate:
    class: 'Invertus\dpdBaltics\Validate\Carrier\PudoValidate'
    arguments:
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.repository.pudo_repository'
      - '@invertus.dpdbaltics.repository.product_repository'

  invertus.dpdbaltics.validate.courier_request.courier_request_validator:
    class: 'Invertus\dpdBaltics\Validate\CourierRequest\CourierRequestValidator'

  invertus.dpdbaltics.validate.weight.cart_weight_validator:
    class: 'Invertus\dpdBaltics\Validate\Weight\CartWeightValidator'

  invertus.dpdbaltics.validate.shipment_data.shipment_data_validator:
    class: 'Invertus\dpdBaltics\Validate\ShipmentData\ShipmentDataValidator'

  invertus.dpdbaltics.validate.phone.phone_number_validator:
    class: 'Invertus\dpdBaltics\Validate\Phone\PhoneNumberValidator'
    arguments:
      - '@dpdbaltics'
      - '@invertus.dpdbaltics.repository.phone_repository'
