services:
  Invertus\dpdBalticsApi\Factory\APIRequest\ClosingManifestFactory:
    class: 'Invertus\dpdBalticsApi\Factory\APIRequest\ClosingManifestFactory'
    arguments:
      - '@Invertus\dpdBaltics\Logger\Logger'
      - '@Invertus\dpdBaltics\Factory\APIParamsFactory'

  Invertus\dpdBalticsApi\Factory\APIRequest\CollectionRequestFactory:
    class: 'Invertus\dpdBalticsApi\Factory\APIRequest\CollectionRequestFactory'
    arguments:
      - '@Invertus\dpdBaltics\Logger\Logger'
      - '@Invertus\dpdBaltics\Factory\APIParamsFactory'


  Invertus\dpdBalticsApi\Factory\APIRequest\CourierRequestFactory:
    class: 'Invertus\dpdBalticsApi\Factory\APIRequest\CourierRequestFactory'
    arguments:
      - '@Invertus\dpdBaltics\Logger\Logger'
      - '@Invertus\dpdBaltics\Factory\APIParamsFactory'


  Invertus\dpdBalticsApi\Factory\APIRequest\ParcelPrintFactory:
    class: 'Invertus\dpdBalticsApi\Factory\APIRequest\ParcelPrintFactory'
    arguments:
      - '@Invertus\dpdBaltics\Logger\Logger'
      - '@Invertus\dpdBaltics\Factory\APIParamsFactory'


  Invertus\dpdBalticsApi\Factory\APIRequest\ParcelShopSearchFactory:
    class: 'Invertus\dpdBalticsApi\Factory\APIRequest\ParcelShopSearchFactory'
    arguments:
      - '@Invertus\dpdBaltics\Logger\Logger'
      - '@Invertus\dpdBaltics\Factory\APIParamsFactory'

  Invertus\dpdBalticsApi\Factory\APIRequest\ShipmentCreationFactory:
    class: 'Invertus\dpdBalticsApi\Factory\APIRequest\ShipmentCreationFactory'
    arguments:
      - '@Invertus\dpdBaltics\Logger\Logger'
      - '@Invertus\dpdBaltics\Factory\APIParamsFactory'